#!/bin/bash
#
# Objective: To create Oracle Non-RAC 12.1.0.2 database on Linux server using OMF (Oracle managed Files)
# Date of last update: 10-May-2018
# Version: 1.2
#
##################################################################################################
# Start of Configuration Section (Update values accordingly after "=" symbol)
#
dbname=abcdev                # specify database name in lower case
sysPassword="Yuz9uva*"       # specify password generated by "pwgen -y" utility
systemPassword="Eim-ag5w"    # specify password generated by "pwgen -y" utility
dbsnmpPassword="Air#o1oo"    # specify password generated by "pwgen -y" utility
#
##################################################################################################
# Start of Coding Section (Don't modify)
#
unset ORACLE_SID
export ORACLE_BASE=/u01/app/oracle
export ORACLE_HOME=/u01/app/oracle/product/12.1.0.2/dbhome_1
export PATH=$ORACLE_HOME/bin:/bin:/usr/bin
#
dbca -silent -createDatabase                                                                     \
  -templateName              ./create_12.1.0.2_db_on_linux_non_rac_omf_version_1.2_template.dbt  \
  -createAsContainerDatabase false                                                               \
  -gdbName                   ${dbname}                                                           \
  -sid                       ${dbname}                                                           \
  -sysPassword               ${sysPassword}                                                      \
  -systemPassword            ${systemPassword}                                                   \
  -emConfiguration           NONE                                                                \
  -dbsnmpPassword            ${dbsnmpPassword}                                                   \
  -dvConfiguration           false                                                               \
  -olsConfiguration          false                                                               \
  -datafileDestination       /u02/oradata                                                        \
  -redoLogFileSize           50                                                                  \
  -recoveryAreaDestination   /u02/fast_recovery_area                                             \
  -storageType               FS                                                                  \
  -characterSet              AL32UTF8                                                            \
  -nationalCharacterSet      AL16UTF16                                                           \
  -listeners                 LISTENER_${dbname^^}                                                \
  -sampleSchema              false                                                               \
  -automaticMemoryManagement true                                                                \
  -totalMemory               4096
##################################################################################################